name: stray_cat_home
description: 校园流浪猫管理app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  # 瀑布流插件
  waterfall_flow: any
  flutter_staggered_grid_view: ^0.6.1
  #网络请求组件
  dio: ^4.0.4
  #字符加密
  crypto: ^3.0.1
  #简单的加载loading
  flutter_easyloading: ^3.0.3
  convert: ^3.0.1
  # 去除网页URL中的“#”
  url_strategy: 0.2.0
  # Localization
  intl: ^0.17.0
  # Dart 常用工具类库
  common_utils: ^2.1.0
  #是一个 Dio 拦截器，它以漂亮、易于阅读的格式记录网络调用。
  pretty_dio_logger: ^1.1.1
  #高德地图插件
  #amap_flutter_location: ^3.0.0
  #amap_flutter_map: ^3.0.0
#  #百度地图
#  flutter_baidu_mapapi_map: ^3.0.0+2
  cupertino_icons: ^1.0.4
  #crypto: ^3.0.1
  #可以显示进度条，逐渐透明显示出来加载的图片
  transparent_image: ^2.0.0
  flutter_svg: ^1.0.3
  #状态管理插件
  provider: ^6.0.2
  # 路由管理
  fluro: ^2.0.3
  # 屏幕适配
  flutter_screenutil: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
flutter:
  uses-material-design: true
  assets:
    - asserts/images/

