name: stray_cat_home
description: 校园流浪猫管理app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  # 瀑布流插件
  waterfall_flow: any
  flutter_staggered_grid_view: ^0.6.1
  #网络请求组件
  dio: ^4.0.4
  #字符加密
  crypto: ^3.0.1
  #简单的加载loading
  flutter_easyloading: ^3.0.3
  convert: ^3.0.1
  # 去除网页URL中的“#”
  url_strategy: 0.2.0
  # Localization
  intl: ^0.17.0
  # Dart 常用工具类库
  common_utils: ^2.1.0
  #是一个 Dio 拦截器，它以漂亮、易于阅读的格式记录网络调用。
  pretty_dio_logger: ^1.1.1
  #高德地图插件
  #amap_flutter_location: ^3.0.0
  #amap_flutter_map: ^3.0.0
#  #百度地图
#  flutter_baidu_mapapi_map: ^3.0.0+2
  cupertino_icons: ^1.0.4
  #crypto: ^3.0.1
  #可以显示进度条，逐渐透明显示出来加载的图片
  transparent_image: ^2.0.0
  flutter_svg: ^1.0.3
#  #状态管理插件
#  provider: ^6.0.2
  #GetX状态管理框架 https://pub.flutter-io.cn/packages/get
  get: ^4.6.1
  # SP键值对存储 https://pub.flutter-io.cn/packages/shared_preferences
  shared_preferences: ^2.0.6
  # 路由管理
  fluro: ^2.0.3
#  # 屏幕适配
#  flutter_screenutil: ^5.3.1
  #toast https://pub.flutter-io.cn/packages/fluttertoast
  fluttertoast: ^8.0.8
  #文件路径管理工具类
  path_provider: ^2.0.2
  # 网络检测 https://pub.flutter-io.cn/packages/connectivity
  connectivity: 3.0.6
  #上拉刷新、下拉加载
  pull_to_refresh: ^2.0.0
  # lottie动画 https://pub.flutter-io.cn/packages/flutter_lottie
  lottie: ^1.2.2
  # https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: ^6.0.9
  # 轮播图
  flutter_swiper_null_safety: ^1.0.2
  #加载webview
  webview_flutter: ^2.0.12


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
flutter:
  uses-material-design: true
  assets:
    - asserts/images/
    - asserts/images/3.0x/
    - asserts/svg/
    - asserts/lottie/lottie_common_load.json
    - asserts/lottie/page_loading_anim.json
    - asserts/lottie/refresh_footer.json
    - asserts/lottie/refresh_head_loading.json
    - asserts/lottie/refresh_empty_page.json
    - asserts/lottie/refresh_error.json
    - asserts/lottie/collect_success.json

